Numpy is a general-purpose array processing package. It provides a high-performance
multi dimensional array object, and tools for working with these arrays. It's the fundamental package for the 
scientific computing with python

Array is a DS that stores values of same data type. In python,
this is main difference between arrays and list.  while python list can
contain values corresponding to different data types, arrays in python
can only contain values corresponding to same data type.

In [2]:
##importing the libary

import numpy as np

ModuleNotFoundError: No module named 'numpy'

In [3]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

In [1]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

In [2]:
import numpy as np


ModuleNotFoundError: No module named 'numpy'

In [1]:
!pip install numpy


  Using cached numpy-1.24.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)


In [2]:
import numpy as np

In [5]:
 lst=[1,2,34,5]
arr= np.array(lst)

In [6]:
type(arr)

numpy.ndarray

In [8]:
lst1= [1,3,45,6,7]
lst2= [2,3,4,5,6]
lst3= [3,3,4,5,6]
arr1=np.array([lst1,lst2,lst3])

In [9]:
arr1.shape

(3, 5)

In [1]:
#indexing

arr[3]

NameError: name 'arr' is not defined

In [2]:
arr1[3]

NameError: name 'arr1' is not defined

In [3]:
import numpy as np

In [5]:
lst1= [1,3,45,6,7]
lst2= [2,3,4,5,6]
lst3= [3,3,4,5,6]
arr1=np.array([lst1,lst2,lst3])

In [6]:
arr1

array([[ 1,  3, 45,  6,  7],
       [ 2,  3,  4,  5,  6],
       [ 3,  3,  4,  5,  6]])

In [7]:
arr1.shape

(3, 5)

In [9]:
arr1

array([[ 1,  3, 45,  6,  7],
       [ 2,  3,  4,  5,  6],
       [ 3,  3,  4,  5,  6]])

In [10]:
arr1[3]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [11]:
arr1[2]

array([3, 3, 4, 5, 6])

In [12]:
arr1[1:]

array([[2, 3, 4, 5, 6],
       [3, 3, 4, 5, 6]])

In [13]:
arr1[0:2]

array([[ 1,  3, 45,  6,  7],
       [ 2,  3,  4,  5,  6]])

In [14]:
arr1[-1]

array([3, 3, 4, 5, 6])

In [16]:
arr1[:-1]

array([[ 1,  3, 45,  6,  7],
       [ 2,  3,  4,  5,  6]])

In [17]:
arr1[::-1]

array([[ 3,  3,  4,  5,  6],
       [ 2,  3,  4,  5,  6],
       [ 1,  3, 45,  6,  7]])

In [19]:
arr1[::-2]

array([[ 3,  3,  4,  5,  6],
       [ 1,  3, 45,  6,  7]])

In [20]:
arr1[:,1]

array([3, 3, 3])

In [21]:
arr1[:,0]

array([1, 2, 3])

In [22]:
arr1[:,3]

array([6, 5, 5])

In [24]:
arr1[1:,1:3]

array([[3, 4],
       [3, 4]])

In [28]:
arr1[1:,3:]

array([[5, 6],
       [5, 6]])

In [ ]:
##EDA pov

In [29]:
arr1

array([[ 1,  3, 45,  6,  7],
       [ 2,  3,  4,  5,  6],
       [ 3,  3,  4,  5,  6]])

In [30]:
arr1<2

array([[ True, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [31]:
arr[arr1<2]

NameError: name 'arr' is not defined

In [32]:
arr1[arr1<2]

array([1])

In [33]:
arr1.reshape(5,3)

array([[ 1,  3, 45],
       [ 6,  7,  2],
       [ 3,  4,  5],
       [ 6,  3,  3],
       [ 4,  5,  6]])

In [34]:
arr1.reshape(5,2)

ValueError: cannot reshape array of size 15 into shape (5,2)

In [37]:
np.arr1(1,10,1)

AttributeError: module 'numpy' has no attribute 'arr1'