In [1]:
!pip install pandas

     |████████████████████████████████| 12.3 MB 2.2 MB/s eta 0:00:01
     |████████████████████████████████| 341 kB 1.4 MB/s eta 0:00:01
     |████████████████████████████████| 502 kB 1.9 MB/s eta 0:00:01


In [2]:
import pandas as pd

In [3]:
import numpy as np

In [1]:
np.arange(0,20)

NameError: name 'np' is not defined

In [2]:
import numpy as np

In [4]:
np.arange(0,20).reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [5]:
import pandas as pd

In [10]:
df=pd.DataFrame(data=np.arange(0,20).reshape(4,5),index=["row1","row2","row3","row4"],columns=["column1",
                                                                                            "column2","column3","column4","column5"])

In [11]:
df.head()

column1  column2  column3  column4  column5
row1        0        1        2        3        4
row2        5        6        7        8        9
row3       10       11       12       13       14
row4       15       16       17       18       19

In [12]:
df.tail()

column1  column2  column3  column4  column5
row1        0        1        2        3        4
row2        5        6        7        8        9
row3       10       11       12       13       14
row4       15       16       17       18       19

In [13]:
type(df)

pandas.core.frame.DataFrame

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, row1 to row4
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   column1  4 non-null      int64
 1   column2  4 non-null      int64
 2   column3  4 non-null      int64
 3   column4  4 non-null      int64
 4   column5  4 non-null      int64
dtypes: int64(5)
memory usage: 192.0+ bytes


In [15]:
df.describe()

column1    column2    column3    column4    column5
count   4.000000   4.000000   4.000000   4.000000   4.000000
mean    7.500000   8.500000   9.500000  10.500000  11.500000
std     6.454972   6.454972   6.454972   6.454972   6.454972
min     0.000000   1.000000   2.000000   3.000000   4.000000
25%     3.750000   4.750000   5.750000   6.750000   7.750000
50%     7.500000   8.500000   9.500000  10.500000  11.500000
75%    11.250000  12.250000  13.250000  14.250000  15.250000
max    15.000000  16.000000  17.000000  18.000000  19.000000

In [16]:
##indexing

# direct by using column name another by row index[loc], rowindex number[iloc]

df.head()


column1  column2  column3  column4  column5
row1        0        1        2        3        4
row2        5        6        7        8        9
row3       10       11       12       13       14
row4       15       16       17       18       19

In [21]:
type(df[['column1','column2','column3']])

pandas.core.frame.DataFrame

In [23]:
type(df['column1'] )#column name

pandas.core.series.Series

In [24]:
df.loc["row1"]

column1    0
column2    1
column3    2
column4    3
column5    4
Name: row1, dtype: int64

In [25]:
df.loc[["row1","row2"]] #using row index name

column1  column2  column3  column4  column5
row1        0        1        2        3        4
row2        5        6        7        8        9

In [26]:
df.head()

column1  column2  column3  column4  column5
row1        0        1        2        3        4
row2        5        6        7        8        9
row3       10       11       12       13       14
row4       15       16       17       18       19

In [29]:
 df.iloc[2:,0:2]

column1  column2
row3       10       11
row4       15       16

In [31]:
df.iloc[0:2,0:2]

column1  column2
row1        0        1
row2        5        6

In [32]:
df.iloc[0:2,2:4]

column3  column4
row1        2        3
row2        7        8

In [34]:
df.iloc[1:3,1:3]

column2  column3
row2        6        7
row3       11       12

In [36]:
#convert DF to arryas
df.iloc[:,1:].values

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14],
       [16, 17, 18, 19]])

In [37]:
#operations

df

column1  column2  column3  column4  column5
row1        0        1        2        3        4
row2        5        6        7        8        9
row3       10       11       12       13       14
row4       15       16       17       18       19

In [38]:
df.isnull().sum()

column1    0
column2    0
column3    0
column4    0
column5    0
dtype: int64

In [43]:
df=pd.DataFrame(data=[[1,np.nan,2],[1,3,4]],index=["row1","row2"],columns=["column1",
                                                                                 "column2","column3",])

In [44]:
df

column1  column2  column3
row1        1      NaN        2
row2        1      3.0        4

In [45]:
df.isnull().sum()

column1    0
column2    1
column3    0
dtype: int64

In [48]:
df.isnull().sum()==0

column1     True
column2    False
column3     True
dtype: bool

In [51]:
df

column1  column2  column3
row1        1      NaN        2
row2        1      3.0        4

In [50]:
df['column3'].value_counts()

column3
2    1
4    1
Name: count, dtype: int64

In [53]:
df['column2'].unique()

array([nan,  3.])

In [56]:
df[df["column2"]>2]

column1  column2  column3
row2        1      3.0        4